import React, { useEffect, useId, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { api, flushOfflineQueue, type Account, type AppState, type SessionInfo, type Settings, type Statistic, type User } from './api.js';
import { gameById, games } from './games/registry.js';
import type { GameManifest } from './games/types.js';
import './styles.css';

type Route = 'home' | 'statistics' | 'settings' | 'sessions' | 'profile' | 'about' | `game:${GameManifest['id']}`;
type ConfirmRequest = { title: string; message: string; confirmLabel: string; danger?: boolean; requirePassword?: boolean; action: () => void | Promise<void> };

function Field({ label, name, type = 'text', autoComplete, minLength, defaultValue }: { label: string; name: string; type?: string; autoComplete?: string; minLength?: number; defaultValue?: string }) {
  return <label className="field"><span>{label}</span><input name={name} type={type} autoComplete={autoComplete} minLength={minLength} defaultValue={defaultValue} required /></label>;
}

function Dialog({ title, children, close, actions }: { title: string; children: React.ReactNode; close: () => void; actions?: React.ReactNode }) {
  const titleId = useId(), panel = useRef<HTMLDivElement>(null);
  useEffect(() => {
    const previous = document.activeElement as HTMLElement | null, focusable = () => [...(panel.current?.querySelectorAll<HTMLElement>('button:not(:disabled), input:not(:disabled), select:not(:disabled), a[href], [tabindex]:not([tabindex="-1"])') ?? [])];
    const backdrop = panel.current?.parentElement, siblings = [...(backdrop?.parentElement?.children ?? [])].filter((element) => element !== backdrop).map((element) => ({ element, hidden: element.getAttribute('aria-hidden'), inert: element.hasAttribute('inert') }));
    for (const { element } of siblings) { element.setAttribute('aria-hidden', 'true'); element.setAttribute('inert', ''); }
    focusable()[0]?.focus();
    const keydown = (event: KeyboardEvent) => {
      if (event.key === 'Escape') { event.preventDefault(); close(); return; }
      if (event.key !== 'Tab') return;
      const items = focusable(); if (!items.length) return;
      const first = items[0]!, last = items.at(-1)!;
      if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); }
      else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); }
    };
    document.addEventListener('keydown', keydown); return () => { document.removeEventListener('keydown', keydown); for (const { element, hidden, inert } of siblings) { if (hidden === null) element.removeAttribute('aria-hidden'); else element.setAttribute('aria-hidden', hidden); if (!inert) element.removeAttribute('inert'); } previous?.focus(); };
  }, [close]);
  return <div className="dialog-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) close(); }}><div className="dialog-panel" ref={panel} role="dialog" aria-modal="true" aria-labelledby={titleId}><div className="dialog-heading"><h2 id={titleId}>{title}</h2><button className="icon-button secondary" aria-label="Close dialog" onClick={close}>×</button></div><div className="dialog-content">{children}</div>{actions && <div className="dialog-actions">{actions}</div>}</div></div>;
}

function ConfirmDialog({ request, close }: { request: ConfirmRequest; close: () => void }) {
  const [password, setPassword] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const approve = async () => { setBusy(true); setError(''); try { if (request.requirePassword) await api.reauthenticate(password); await request.action(); close(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'The action could not be completed.'); setBusy(false); } };
  return <Dialog title={request.title} close={close} actions={<><button className="secondary" disabled={busy} onClick={close}>Cancel</button><button className={request.danger ? 'danger' : ''} disabled={busy || Boolean(request.requirePassword && password.length < 12)} onClick={() => void approve()}>{busy ? 'Checking…' : request.confirmLabel}</button></>}><p>{request.message}</p>{request.requirePassword && <label className="field"><span>Current password</span><input type="password" autoComplete="current-password" minLength={12} value={password} onChange={(event) => setPassword(event.target.value)} /></label>}{error && <p className="form-error" role="alert">{error}</p>}</Dialog>;
}

function AccessScreen({ setup, onReady }: { setup: boolean; onReady: (user: User) => void }) {
  const [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const submit = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault(); setBusy(true); setError(''); const data = new FormData(event.currentTarget);
    try {
      if (setup) await api.setup({ username: String(data.get('username')), displayName: String(data.get('displayName')), password: String(data.get('password')), setupSecret: String(data.get('setupSecret')) });
      const session = await api.login({ username: String(data.get('username')), password: String(data.get('password')) }); onReady(session.user);
    } catch (cause) { setError(cause instanceof Error ? cause.message : 'Access could not be completed.'); } finally { setBusy(false); }
  };
  return <main className="access-layout"><section className="access-card"><img src="/playiku-icon.png" alt="" /><p className="eyebrow">Playiku</p><h1>{setup ? 'Set up Playiku' : 'Welcome back'}</h1><p>{setup ? 'Create the first administrator for this private game library.' : 'Sign in to continue your games.'}</p><form onSubmit={submit}>{setup && <Field label="Display name" name="displayName" autoComplete="name" />}<Field label="Username" name="username" autoComplete="username" />{setup && <Field label="One-time setup secret" name="setupSecret" type="password" autoComplete="off" minLength={32} />}<Field label={setup ? 'Administrator password' : 'Password'} name="password" type="password" autoComplete={setup ? 'new-password' : 'current-password'} minLength={12} />{error && <p className="form-error" role="alert">{error}</p>}<button className="wide" disabled={busy}>{busy ? 'Please wait…' : setup ? 'Create administrator' : 'Sign in'}</button></form></section></main>;
}

function GameCard({ game, favorite, statistic, resume, onOpen, onFavorite }: { game: GameManifest; favorite: boolean; statistic?: Statistic; resume?: boolean; onOpen: () => void; onFavorite: () => void }) {
  return <article className="game-card"><button className="favorite-button" aria-label={favorite ? `Remove ${game.name} from favorites` : `Add ${game.name} to favorites`} aria-pressed={favorite} onClick={onFavorite}>{favorite ? '★' : '☆'}</button><button className="game-card-main" onClick={onOpen}><span className={`game-icon game-icon-${game.id}`} aria-hidden="true"><svg viewBox="0 0 24 24" focusable="false"><path d={game.icon} /></svg></span><span><strong>{game.name}</strong><small>{game.description}</small>{resume ? <em>Continue saved game</em> : statistic && <em>{statistic.best_score ? `Best ${statistic.best_score}` : `${statistic.games_played} played`}</em>}</span></button></article>;
}
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="library-section"><h2>{title}</h2>{children}</section>; }

function Home({ state, openGame, toggleFavorite }: { state: AppState; openGame: (id: GameManifest['id'], resume?: boolean) => void; toggleFavorite: (id: GameManifest['id']) => void }) {
  const byStats = new Map(state.statistics.map((item) => [item.game_id, item])), favorites = games.filter((game) => state.favorites.includes(game.id));
  const continuing = state.activeSessions.map((session) => gameById[session.gameId as GameManifest['id']]).filter(Boolean), recent = state.statistics.slice(0, 5).map((statistic) => gameById[statistic.game_id as GameManifest['id']]).filter(Boolean);
  const cards = (items: GameManifest[], resume = false) => <div className="game-grid">{items.map((game) => <GameCard key={game.id} game={game} favorite={state.favorites.includes(game.id)} statistic={byStats.get(game.id)} resume={resume} onOpen={() => openGame(game.id, resume || state.settings.autoResume)} onFavorite={() => toggleFavorite(game.id)} />)}</div>;
  return <main id="main"><div className="page-heading"><p className="eyebrow">Choose a game</p><h1>Games</h1><p>Six quick games, ready when you are.</p></div>{continuing.length > 0 && <Section title="Continue">{cards(continuing, true)}</Section>}{favorites.length > 0 && <Section title="Favorites">{cards(favorites)}</Section>}<Section title="All games">{cards(games)}</Section>{recent.length > 0 && <Section title="Recent">{cards(recent)}</Section>}</main>;
}

function Statistics({ statistics }: { statistics: Statistic[] }) {
  const played = statistics.reduce((sum, item) => sum + item.games_played, 0), won = statistics.reduce((sum, item) => sum + item.games_won, 0), time = statistics.reduce((sum, item) => sum + item.total_play_ms, 0), favorite = [...statistics].sort((a, b) => b.games_played - a.games_played)[0], longest = Math.max(0, ...statistics.map((item) => item.longest_streak));
  const milestones = [{ label: 'First win', earned: won >= 1 }, { label: 'Ten games', earned: played >= 10 }, { label: 'On a roll', earned: longest >= 3 }, { label: '2048', earned: (statistics.find((item) => item.game_id === '2048')?.best_score ?? 0) >= 2048 }];
  return <main id="main"><div className="page-heading"><p className="eyebrow">Your activity</p><h1>Statistics</h1></div>{statistics.length === 0 ? <section className="state-view"><h2>No games played yet</h2><p>Start any game and your private statistics will appear here.</p></section> : <><div className="stat-grid"><article><span>Games played</span><strong>{played}</strong></article><article><span>Games won</span><strong>{won}</strong></article><article><span>Play time</span><strong>{Math.floor(time / 3_600_000)}h {Math.floor(time / 60_000) % 60}m</strong></article><article><span>Favorite game</span><strong>{favorite ? gameById[favorite.game_id as GameManifest['id']]?.name : '—'}</strong></article><article><span>Longest streak</span><strong>{longest}</strong></article></div><Section title="By game"><div className="table-wrap"><table><thead><tr><th>Game</th><th>Played</th><th>Won</th><th>Best score</th><th>Best time</th></tr></thead><tbody>{statistics.map((item) => <tr key={item.game_id}><th>{gameById[item.game_id as GameManifest['id']]?.name ?? item.game_id}</th><td>{item.games_played}</td><td>{item.games_won}</td><td>{item.best_score ?? '—'}</td><td>{item.best_time_ms ? `${Math.round(item.best_time_ms / 1000)}s` : '—'}</td></tr>)}</tbody></table></div></Section></>}<Section title="Milestones"><div className="milestone-grid">{milestones.map((item) => <article className={item.earned ? 'earned' : ''} key={item.label}><span aria-hidden="true">{item.earned ? '◆' : '◇'}</span><strong>{item.label}</strong><small>{item.earned ? 'Unlocked' : 'Not yet unlocked'}</small></article>)}</div></Section></main>;
}

function Toggle({ label, description, value, set }: { label: string; description?: string; value: boolean; set: (value: boolean) => void }) { return <label className="toggle"><span><strong>{label}</strong>{description && <small>{description}</small>}</span><input type="checkbox" checked={value} onChange={(event) => set(event.target.checked)} /><i aria-hidden="true" /></label>; }

function AccountManager({ requestDelete }: { requestDelete: (account: Account, refresh: () => void) => void }) {
  const [accounts, setAccounts] = useState<Account[]>([]), [error, setError] = useState(''), [loading, setLoading] = useState(true);
  const refresh = () => { setLoading(true); void api.accounts().then(setAccounts).catch((cause) => setError(cause instanceof Error ? cause.message : 'Accounts could not be loaded.')).finally(() => setLoading(false)); };
  useEffect(refresh, []);
  const create = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(''); const form = event.currentTarget, data = new FormData(form); void api.createAccount({ displayName: String(data.get('displayName')), username: String(data.get('username')), password: String(data.get('password')) }).then(() => { form.reset(); refresh(); }).catch((cause) => setError(cause instanceof Error ? cause.message : 'Account could not be created.')); };
  return <section><h2>Administration</h2><h3>Accounts</h3><p>Create private accounts for other people using this instance.</p><form className="account-form" onSubmit={create}><Field label="Display name" name="displayName" autoComplete="off" /><Field label="Username" name="username" autoComplete="off" /><Field label="Initial password" name="password" type="password" autoComplete="new-password" minLength={12} />{error && <p className="form-error" role="alert">{error}</p>}<button>Create account</button></form>{loading ? <p role="status">Loading accounts…</p> : <ul className="account-list">{accounts.map((account) => <li key={account.id}><span><strong>{account.displayName}</strong><small>@{account.username} · {account.role}</small></span>{account.role !== 'admin' && <button className="secondary danger" onClick={() => requestDelete(account, refresh)}>Delete</button>}</li>)}</ul>}</section>;
}

function SettingsPage({ settings, user, save, requestClear, requestDeleteAccount }: { settings: Settings; user: User; save: (value: Settings) => void; requestClear: (type: 'sessions' | 'statistics' | 'all') => void; requestDeleteAccount: (account: Account, refresh: () => void) => void }) {
  const update = <K extends keyof Settings>(key: K, value: Settings[K]) => save({ ...settings, [key]: value });
  const updateDefault = <K extends keyof Settings['defaults']>(key: K, value: Settings['defaults'][K]) => update('defaults', { ...settings.defaults, [key]: value });
  return <main id="main"><div className="page-heading"><p className="eyebrow">Make it yours</p><h1>Settings</h1></div><div className="settings-grid">
    <section><h2>Appearance</h2><label className="field"><span>Theme</span><select value={settings.theme} onChange={(event) => update('theme', event.target.value as Settings['theme'])}><option value="lavender">Lavender</option><option value="mint">Mint</option><option value="sky">Sky</option><option value="amber">Amber</option><option value="rose">Rose</option><option value="graphite">Graphite</option></select></label><label className="field"><span>Mode</span><select value={settings.mode} onChange={(event) => update('mode', event.target.value as Settings['mode'])}><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select></label><Toggle label="Animations" value={settings.animations} set={(value) => update('animations', value)} /><Toggle label="Reduced motion" description="Minimizes movement independently of your system setting." value={settings.reducedMotion} set={(value) => update('reducedMotion', value)} /></section>
    <section><h2>Gameplay</h2><Toggle label="Sound effects" value={settings.sound} set={(value) => update('sound', value)} /><Toggle label="Haptic feedback" value={settings.haptics} set={(value) => update('haptics', value)} /><Toggle label="Highlight Sudoku mistakes" value={settings.showMistakes} set={(value) => update('showMistakes', value)} /><Toggle label="Confirm replacement games" description="Ask before replacing a saved or active game." value={settings.confirmNewGames} set={(value) => update('confirmNewGames', value)} /><Toggle label="Continue unfinished games automatically" value={settings.autoResume} set={(value) => update('autoResume', value)} /><h3>Default games</h3><div className="default-grid"><label className="field"><span>Sudoku</span><select value={settings.defaults.sudoku} onChange={(event) => updateDefault('sudoku', event.target.value as Settings['defaults']['sudoku'])}><option>Easy</option><option>Medium</option><option>Hard</option><option>Expert</option></select></label><label className="field"><span>Minesweeper</span><select value={settings.defaults.minesweeper} onChange={(event) => updateDefault('minesweeper', event.target.value as Settings['defaults']['minesweeper'])}><option>Beginner</option><option>Intermediate</option><option>Expert</option><option>Custom</option></select></label><label className="field"><span>Nonogram</span><select value={settings.defaults.nonogram} onChange={(event) => updateDefault('nonogram', Number(event.target.value) as 5 | 10 | 15)}><option value={5}>5 × 5</option><option value={10}>10 × 10</option><option value={15}>15 × 15</option></select></label><label className="field"><span>Snake</span><select value={settings.defaults.snake} onChange={(event) => updateDefault('snake', Number(event.target.value) as 16 | 22 | 28)}><option value={16}>Small</option><option value={22}>Medium</option><option value={28}>Large</option></select></label><label className="field"><span>Solitaire</span><select value={settings.defaults.solitaireDraw} onChange={(event) => updateDefault('solitaireDraw', Number(event.target.value) as 1 | 3)}><option value={1}>Draw 1</option><option value={3}>Draw 3</option></select></label></div></section>
    <section><h2>Privacy</h2><p>Game data stays on this Playiku instance and is never sent to analytics services.</p><div className="danger-actions"><button className="secondary" onClick={() => requestClear('sessions')}>Delete saved games</button><button className="secondary danger" onClick={() => requestClear('statistics')}>Delete statistics</button><button className="danger" onClick={() => requestClear('all')}>Delete all game data</button></div></section>
    {user.role === 'admin' && <AccountManager requestDelete={requestDeleteAccount} />}
  </div></main>;
}

function ProfilePage({ user, update }: { user: User; update: (user: User) => void }) {
  const [notice, setNotice] = useState('');
  const submit = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const name = String(new FormData(event.currentTarget).get('displayName')); setNotice(''); void api.updateProfile(name).then((next) => { update(next); setNotice('Profile saved.'); }).catch((cause) => setNotice(cause instanceof Error ? cause.message : 'Profile could not be saved.')); };
  return <main id="main"><div className="page-heading"><p className="eyebrow">Your account</p><h1>Profile</h1></div><section className="profile-card"><span className="profile-avatar" aria-hidden="true">{user.displayName.slice(0, 1).toUpperCase()}</span><form onSubmit={submit}><Field label="Display name" name="displayName" autoComplete="name" defaultValue={user.displayName} /><p className="account-identity">Username: <strong>@{user.username}</strong> · {user.role}</p><p>Your preferences, statistics, favorites, and active games are private to this account.</p>{notice && <p role="status">{notice}</p>}<button>Save profile</button></form></section></main>;
}

function SessionsPage({ onCurrentRevoked }: { onCurrentRevoked: () => void }) {
  const [sessions, setSessions] = useState<SessionInfo[]>([]), [error, setError] = useState(''), [confirm, setConfirm] = useState<SessionInfo>();
  const refresh = () => void api.sessions().then(setSessions).catch((cause) => setError(cause instanceof Error ? cause.message : 'Sessions could not be loaded.'));
  useEffect(refresh, []);
  const revoke = (session: SessionInfo) => { if (session.current) { onCurrentRevoked(); return; } void api.revokeSession(session.id).then(refresh).catch((cause) => setError(cause instanceof Error ? cause.message : 'Session could not be revoked.')); };
  return <main id="main"><div className="page-heading"><p className="eyebrow">Account security</p><h1>Sessions</h1><p>Review and revoke signed-in sessions for this account.</p></div><section className="sessions-card">{error && <p className="form-error" role="alert">{error}</p>}{sessions.length ? <ul className="session-list">{sessions.map((session) => <li key={session.id}><span><strong>{session.current ? 'This device' : 'Signed-in session'}</strong><small>Last active {new Date(session.lastSeenAt).toLocaleString()} · expires {new Date(session.expiresAt).toLocaleDateString()}</small></span><button className="secondary danger" onClick={() => setConfirm(session)}>{session.current ? 'Sign out' : 'Revoke'}</button></li>)}</ul> : !error && <p role="status">Loading sessions…</p>}</section>{confirm && <ConfirmDialog request={{ title: confirm.current ? 'Sign out this device?' : 'Revoke this session?', message: confirm.current ? 'You will return to the sign-in screen.' : 'Confirm your current password to revoke that session.', confirmLabel: confirm.current ? 'Sign out' : 'Revoke session', danger: true, requirePassword: !confirm.current, action: () => revoke(confirm) }} close={() => setConfirm(undefined)} />}</main>;
}

function About() {
  const [manifest, setManifest] = useState<{ version: string; buildDate: string; gitSha: string; license: string; repository: string }>(), [error, setError] = useState(false);
  useEffect(() => { void api.manifest().then(setManifest).catch(() => setError(true)); }, []);
  return <main id="main"><div className="page-heading"><p className="eyebrow">About this app</p><h1>Playiku</h1><p>Casual Games</p></div><section className="about-card"><img src="/playiku-icon.png" alt="Playiku game controller icon" />{error ? <div className="state-view compact"><h2>Build details unavailable</h2><p>Reconnect to the Playiku server and try again.</p></div> : <dl><div><dt>Version</dt><dd>{manifest?.version ?? 'Loading…'}</dd></div><div><dt>Build date</dt><dd>{manifest?.buildDate ?? 'Loading…'}</dd></div><div><dt>Git commit</dt><dd>{manifest?.gitSha ?? 'Loading…'}</dd></div><div><dt>License</dt><dd>{manifest?.license ?? 'Apache-2.0'}</dd></div></dl>}<a href={manifest?.repository ?? 'https://github.com/MaroIshiku/playiku'}>View repository</a><p>Third-party license details are included in the repository and release SBOM.</p></section></main>;
}

function GamePage({ id, initialState, bestScore, settings, back, refresh }: { id: GameManifest['id']; initialState?: unknown; bestScore?: number; settings: Settings; back: () => void; refresh: () => void }) {
  const game = gameById[id], Component = game.component, saveTimer = useRef<number | undefined>(undefined), finished = useRef(false);
  const [gameKey, setGameKey] = useState(0), [fresh, setFresh] = useState(false), [daily, setDaily] = useState<{ date: string; seed: string; completed: boolean }>(), [dailyStatus, setDailyStatus] = useState<{ date: string; seed: string; completed: boolean }>(), [showTips, setShowTips] = useState(false), [confirmNew, setConfirmNew] = useState(false), [result, setResult] = useState<{ outcome: 'won' | 'lost'; text: string }>();
  useEffect(() => { finished.current = false; if (initialState === undefined) void api.statistic({ gameId: id, outcome: 'started' }); if (game.supportsDailyChallenge) void api.daily(id).then(setDailyStatus); return () => clearTimeout(saveTimer.current); }, [id]);
  const preferences = { showMistakes: settings.showMistakes, sudokuDifficulty: settings.defaults.sudoku, minesweeperDifficulty: settings.defaults.minesweeper, nonogramSize: settings.defaults.nonogram, snakeSize: settings.defaults.snake, solitaireDraw: settings.defaults.solitaireDraw };
  const save = (next: unknown) => { if (daily) return; clearTimeout(saveTimer.current); if (game.supportsResume) saveTimer.current = window.setTimeout(() => void api.saveGame(id, next), 350); };
  const finish = (details: { outcome: 'won' | 'lost'; score?: number; durationMs?: number }) => {
    if (finished.current) return; finished.current = true; clearTimeout(saveTimer.current);
    if (settings.haptics && 'vibrate' in navigator) navigator.vibrate(details.outcome === 'won' ? [35, 30, 70] : [45]);
    if (settings.sound) { const AudioContext = window.AudioContext ?? (window as typeof window & { webkitAudioContext?: typeof window.AudioContext }).webkitAudioContext; if (AudioContext) { const context = new AudioContext(), oscillator = context.createOscillator(), gain = context.createGain(); oscillator.frequency.value = details.outcome === 'won' ? 660 : 220; gain.gain.value = .035; oscillator.connect(gain).connect(context.destination); oscillator.start(); oscillator.stop(context.currentTime + .12); oscillator.onended = () => void context.close(); } }
    const operations: Promise<unknown>[] = [api.statistic({ gameId: id, outcome: details.outcome, dailyDate: daily?.date, score: details.score, durationMs: details.durationMs })];
    if (!daily && game.supportsResume) operations.push(api.saveGame(id, {}, true));
    setResult({ outcome: details.outcome, text: details.outcome === 'won' ? 'Round complete — nicely played!' : 'Round finished — ready for another try.' });
    if (daily && details.outcome === 'won') { setDaily((value) => value && { ...value, completed: true }); setDailyStatus((value) => value && { ...value, completed: true }); }
    void Promise.all(operations).then(refresh);
  };
  const restart = () => { clearTimeout(saveTimer.current); finished.current = false; setResult(undefined); setFresh(true); setGameKey((value) => value + 1); void api.statistic({ gameId: id, outcome: 'started' }); if (!daily && game.supportsResume) void api.saveGame(id, {}, true); };
  const requestRestart = () => { if (settings.confirmNewGames) setConfirmNew(true); else restart(); };
  const startDaily = () => {
    const launch = (challenge: { date: string; seed: string; completed: boolean }) => { setDailyStatus(challenge); if (challenge.completed) { setResult({ outcome: 'won', text: `Daily challenge for ${challenge.date} is already complete.` }); return; } clearTimeout(saveTimer.current); finished.current = false; setDaily(challenge); setResult(undefined); setFresh(true); setGameKey((value) => value + 1); void api.statistic({ gameId: id, outcome: 'started' }); };
    if (dailyStatus) launch(dailyStatus); else void api.daily(id).then(launch);
  };
  return <><header className="game-header"><button className="icon-button secondary" aria-label="Back to games" onClick={back}>←</button><div><h1>{game.name}{daily ? ` · Daily ${daily.date}` : ''}</h1><small>{game.controls}</small></div><button className="secondary compact-action" onClick={() => setShowTips(true)}>How to play</button>{game.supportsDailyChallenge && <button className="secondary compact-action" disabled={Boolean(dailyStatus?.completed)} onClick={startDaily}>{dailyStatus?.completed ? 'Daily complete' : daily ? 'Daily active' : 'Daily challenge'}</button>}<button className="compact-action" onClick={requestRestart}>{daily ? 'Restart' : 'New game'}</button></header><main id="main" className="game-main">{result && <div className={`round-result ${result.outcome}`} role="status">{result.text}</div>}<Component key={gameKey} initialState={fresh ? undefined : initialState} dailySeed={daily?.seed} reducedMotion={settings.reducedMotion} bestScore={bestScore} preferences={preferences} onState={save} onFinish={finish} /></main>{showTips && <Dialog title={`How to play ${game.name}`} close={() => setShowTips(false)} actions={<button onClick={() => setShowTips(false)}>Got it</button>}><p>{game.description}</p><ol className="tips-list">{game.tips.map((tip) => <li key={tip}>{tip}</li>)}</ol><p className="control-note"><strong>Controls:</strong> {game.controls}</p></Dialog>}{confirmNew && <ConfirmDialog request={{ title: daily ? 'Restart this Daily challenge?' : 'Start a new game?', message: daily ? 'Your current Daily progress will be reset. The challenge itself stays the same today.' : game.supportsResume ? 'Your current saved game will be replaced.' : 'Your current round will end.', confirmLabel: daily ? 'Restart' : 'New game', action: restart }} close={() => setConfirmNew(false)} />}</>;
}

function Shell({ user, onUser, onLogout }: { user: User; onUser: (user: User) => void; onLogout: () => void }) {
  const [route, setRoute] = useState<Route>('home'), [state, setState] = useState<AppState>(), [menu, setMenu] = useState(false), [notice, setNotice] = useState(''), [loadError, setLoadError] = useState(''), [resumeGame, setResumeGame] = useState(false), [confirm, setConfirm] = useState<ConfirmRequest>();
  const refresh = () => { setLoadError(''); void api.state().then(setState).catch((cause) => setLoadError(cause instanceof Error ? cause.message : 'Could not load game data.')); };
  useEffect(refresh, []);
  useEffect(() => {
    if (!state) return;
    const media = window.matchMedia('(prefers-color-scheme: dark)'), apply = () => { document.documentElement.dataset.resolvedMode = state.settings.mode === 'system' ? (media.matches ? 'dark' : 'light') : state.settings.mode; };
    document.documentElement.dataset.theme = state.settings.theme; document.documentElement.dataset.mode = state.settings.mode; document.documentElement.dataset.motion = state.settings.reducedMotion || !state.settings.animations ? 'reduced' : 'full'; apply(); media.addEventListener('change', apply); return () => media.removeEventListener('change', apply);
  }, [state]);
  useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key === 'Escape') setMenu(false); }; window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close); }, []);
  const openGame = (id: GameManifest['id'], resume = false) => {
    const launch = () => { setResumeGame(resume); setRoute(`game:${id}`); window.scrollTo(0, 0); };
    const hasSavedGame = state?.activeSessions.some((session) => session.gameId === id);
    if (!resume && hasSavedGame) {
      const replace = async () => { await api.saveGame(id, {}, true); launch(); };
      if (state?.settings.confirmNewGames) setConfirm({ title: `Replace saved ${gameById[id].name} game?`, message: 'The unfinished saved game will be removed before a new one starts.', confirmLabel: 'Start new game', action: replace }); else replace();
    } else launch();
  };
  if (!state) return loadError ? <main className="loading-screen state-view"><h1>Playiku could not load</h1><p role="alert">{loadError}</p><button onClick={refresh}>Try again</button></main> : <main className="loading-screen"><img src="/playiku-icon.png" alt="" /><p role="status">Loading your games…</p></main>;
  if (route.startsWith('game:')) { const id = route.slice(5) as GameManifest['id'], saved = resumeGame ? state.activeSessions.find((item) => item.gameId === id)?.state : undefined; return <GamePage id={id} initialState={saved} bestScore={state.statistics.find((item) => item.game_id === id)?.best_score ?? undefined} settings={state.settings} back={() => { refresh(); setRoute('home'); }} refresh={refresh} />; }
  const navigate = (next: Route) => { setRoute(next); setMenu(false); window.scrollTo(0, 0); };
  const saveSettings = (settings: Settings) => { setState({ ...state, settings }); void api.saveSettings(settings).catch(() => { setNotice('Settings could not be saved.'); refresh(); }); };
  const requestClear = (type: 'sessions' | 'statistics' | 'all') => setConfirm({ title: type === 'sessions' ? 'Delete saved games?' : type === 'statistics' ? 'Delete statistics?' : 'Delete all game data?', message: type === 'sessions' ? 'Confirm your password to remove all resumable game progress.' : type === 'statistics' ? 'Confirm your password to remove statistics, Daily results, and milestones.' : 'Confirm your password to remove saved games, statistics, Daily results, and milestones. This cannot be undone.', confirmLabel: 'Delete data', danger: true, requirePassword: true, action: async () => { await api.clearHistory(type); setNotice('Game data deleted.'); refresh(); } });
  const requestDeleteAccount = (account: Account, after: () => void) => setConfirm({ title: `Delete ${account.displayName}?`, message: 'Confirm your password to permanently remove the account and all associated game data.', confirmLabel: 'Delete account', danger: true, requirePassword: true, action: async () => { await api.deleteAccount(account.id); after(); } });
  return <><a className="skip-link" href="#main">Skip to content</a><header className="app-header"><button className="brand" onClick={() => navigate('home')}><img src="/playiku-icon.png" alt="" /><span><strong>Playiku</strong><small>Casual Games</small></span></button><nav aria-label="Primary"><button className="nav-button" aria-current={route === 'home' ? 'page' : undefined} onClick={() => navigate('home')}>Games</button><button className="nav-button desktop-nav" aria-current={route === 'statistics' ? 'page' : undefined} onClick={() => navigate('statistics')}>Statistics</button></nav><div className="profile-wrap"><button className="profile-button" aria-label="Open profile menu" aria-expanded={menu} aria-controls="profile-menu" onClick={() => setMenu((value) => !value)}><span>{user.displayName.slice(0, 1).toUpperCase()}</span><em>{user.displayName}</em></button>{menu && <nav id="profile-menu" className="profile-menu" aria-label="Profile"><button onClick={() => navigate('profile')}>Profile</button><button onClick={() => navigate('statistics')}>Statistics</button><button onClick={() => navigate('settings')}>Settings</button><button onClick={() => navigate('sessions')}>Sessions</button><button onClick={() => navigate('settings')}>Theme</button><button onClick={() => navigate('about')}>About</button><hr /><button onClick={onLogout}>Logout</button></nav>}</div></header>{notice && <div className="toast" role="status"><span>{notice}</span><button aria-label="Dismiss message" onClick={() => setNotice('')}>×</button></div>}{route === 'home' && <Home state={state} openGame={openGame} toggleFavorite={(id) => { const favorite = !state.favorites.includes(id); setState({ ...state, favorites: favorite ? [...state.favorites, id] : state.favorites.filter((item) => item !== id) }); void api.favorite(id, favorite).catch(refresh); }} />}{route === 'statistics' && <Statistics statistics={state.statistics} />}{route === 'settings' && <SettingsPage settings={state.settings} user={user} save={saveSettings} requestClear={requestClear} requestDeleteAccount={requestDeleteAccount} />}{route === 'profile' && <ProfilePage user={user} update={onUser} />}{route === 'sessions' && <SessionsPage onCurrentRevoked={onLogout} />}{route === 'about' && <About />}{confirm && <ConfirmDialog request={confirm} close={() => setConfirm(undefined)} />}</>;
}

function App() {
  const [status, setStatus] = useState<'loading' | 'setup' | 'login' | 'ready'>('loading'), [user, setUser] = useState<User>(), [fatal, setFatal] = useState('');
  useEffect(() => {
    void api.setupStatus().then(async ({ required }) => { if (required) setStatus('setup'); else { try { const session = await api.session(); setUser(session.user); setStatus('ready'); } catch { setStatus('login'); } } }).catch((cause) => setFatal(cause instanceof Error ? cause.message : 'Playiku could not start.'));
    const register = () => { if ('serviceWorker' in navigator) void navigator.serviceWorker.register('/sw.js'); }, online = () => void flushOfflineQueue();
    if (document.readyState === 'complete') register(); else window.addEventListener('load', register);
    window.addEventListener('online', online); return () => { window.removeEventListener('load', register); window.removeEventListener('online', online); };
  }, []);
  if (fatal) return <main className="loading-screen state-view"><h1>Playiku could not start</h1><p role="alert">{fatal}</p><button onClick={() => window.location.reload()}>Reload</button></main>;
  if (status === 'loading') return <main className="loading-screen"><img src="/playiku-icon.png" alt="" /><p role="status">Starting Playiku…</p></main>;
  if (status === 'setup' || status === 'login') return <AccessScreen setup={status === 'setup'} onReady={(next) => { setUser(next); setStatus('ready'); }} />;
  return user ? <Shell user={user} onUser={setUser} onLogout={() => { void api.logout().catch(() => undefined).finally(() => { setUser(undefined); setStatus('login'); }); }} /> : null;
}

createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);
