import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { api, flushOfflineQueue, type Account, type AppState, type Settings, type Statistic, type User } from './api.js';
import { gameById, games } from './games/registry.js';
import type { GameManifest } from './games/types.js';
import './styles.css';

type Route = 'home' | 'statistics' | 'settings' | 'profile' | 'about' | `game:${GameManifest['id']}`;

function Field({ label, name, type = 'text', autoComplete, minLength }: { label: string; name: string; type?: string; autoComplete?: string; minLength?: number }) {
  return <label className="field"><span>{label}</span><input name={name} type={type} autoComplete={autoComplete} minLength={minLength} required /></label>;
}

function AccessScreen({ setup, onReady }: { setup: boolean; onReady: (user: User) => void }) {
  const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault(); setBusy(true); setError(''); const data = new FormData(event.currentTarget);
    try {
      if (setup) await api.setup({ username: String(data.get('username')), displayName: String(data.get('displayName')), password: String(data.get('password')), setupSecret: String(data.get('setupSecret')) });
      const session = await api.login({ username: String(data.get('username')), password: String(data.get('password')) }); onReady(session.user);
    } catch (cause) { setError(cause instanceof Error ? cause.message : 'Access could not be completed.'); } finally { setBusy(false); }
  };
  return <main className="access-layout"><section className="access-card"><img src="/playiku-icon.png" alt="" /><p className="eyebrow">Playiku</p><h1>{setup ? 'Set up Playiku' : 'Welcome back'}</h1><p>{setup ? 'Create the first administrator for this private game library.' : 'Sign in to continue your games.'}</p><form onSubmit={submit}>{setup && <Field label="Display name" name="displayName" autoComplete="name" />}<Field label="Username" name="username" autoComplete="username" />{setup && <Field label="One-time setup secret" name="setupSecret" type="password" autoComplete="off" minLength={32} />}<Field label={setup ? 'Administrator password' : 'Password'} name="password" type="password" autoComplete={setup ? 'new-password' : 'current-password'} minLength={12} />{error && <p className="form-error" role="alert">{error}</p>}<button className="wide" disabled={busy}>{busy ? 'Please wait…' : setup ? 'Create administrator' : 'Sign in'}</button></form></section></main>;
}

function GameCard({ game, favorite, statistic, onOpen, onFavorite }: { game: GameManifest; favorite: boolean; statistic?: Statistic; onOpen: () => void; onFavorite: () => void }) {
  return <article className="game-card"><button className="favorite-button" aria-label={favorite ? `Remove ${game.name} from favorites` : `Add ${game.name} to favorites`} aria-pressed={favorite} onClick={onFavorite}>{favorite ? '★' : '☆'}</button><button className="game-card-main" onClick={onOpen}><span className={`game-icon game-icon-${game.id}`}>{game.icon}</span><span><strong>{game.name}</strong><small>{game.description}</small>{statistic && <em>{statistic.best_score ? `Best ${statistic.best_score}` : `${statistic.games_played} played`}</em>}</span></button></article>;
}
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="library-section"><h2>{title}</h2>{children}</section>; }

function Home({ state, openGame, toggleFavorite }: { state: AppState; openGame: (id: GameManifest['id']) => void; toggleFavorite: (id: GameManifest['id']) => void }) {
  const byStats = new Map(state.statistics.map((item) => [item.game_id, item])), favorites = games.filter((game) => state.favorites.includes(game.id));
  const continuing = state.activeSessions.map((session) => gameById[session.gameId as GameManifest['id']]).filter(Boolean), recent = state.statistics.slice(0, 5).map((statistic) => gameById[statistic.game_id as GameManifest['id']]).filter(Boolean);
  const cards = (items: GameManifest[]) => <div className="game-grid">{items.map((game) => <GameCard key={game.id} game={game} favorite={state.favorites.includes(game.id)} statistic={byStats.get(game.id)} onOpen={() => openGame(game.id)} onFavorite={() => toggleFavorite(game.id)} />)}</div>;
  return <main id="main"><div className="page-heading"><p className="eyebrow">Choose a game</p><h1>Games</h1><p>Six quick games, ready when you are.</p></div>{continuing.length > 0 && <Section title="Continue">{cards(continuing)}</Section>}{favorites.length > 0 && <Section title="Favorites">{cards(favorites)}</Section>}<Section title="All games">{cards(games)}</Section>{recent.length > 0 && <Section title="Recent">{cards(recent)}</Section>}</main>;
}

function Statistics({ statistics }: { statistics: Statistic[] }) {
  const played = statistics.reduce((sum, item) => sum + item.games_played, 0), won = statistics.reduce((sum, item) => sum + item.games_won, 0), time = statistics.reduce((sum, item) => sum + item.total_play_ms, 0), favorite = [...statistics].sort((a, b) => b.games_played - a.games_played)[0], longest = Math.max(0, ...statistics.map((item) => item.longest_streak));
  const milestones = [{ label: 'First win', earned: won >= 1 }, { label: 'Ten games', earned: played >= 10 }, { label: 'On a roll', earned: longest >= 3 }, { label: '2048', earned: (statistics.find((item) => item.game_id === '2048')?.best_score ?? 0) >= 2048 }];
  return <main id="main"><div className="page-heading"><p className="eyebrow">Your activity</p><h1>Statistics</h1></div><div className="stat-grid"><article><span>Games played</span><strong>{played}</strong></article><article><span>Games won</span><strong>{won}</strong></article><article><span>Play time</span><strong>{Math.floor(time / 3_600_000)}h {Math.floor(time / 60_000) % 60}m</strong></article><article><span>Favorite game</span><strong>{favorite ? gameById[favorite.game_id as GameManifest['id']]?.name : '—'}</strong></article><article><span>Longest streak</span><strong>{longest}</strong></article></div><Section title="By game"><div className="table-wrap"><table><thead><tr><th>Game</th><th>Played</th><th>Won</th><th>Best score</th><th>Best time</th></tr></thead><tbody>{statistics.map((item) => <tr key={item.game_id}><th>{gameById[item.game_id as GameManifest['id']]?.name ?? item.game_id}</th><td>{item.games_played}</td><td>{item.games_won}</td><td>{item.best_score ?? '—'}</td><td>{item.best_time_ms ? `${Math.round(item.best_time_ms / 1000)}s` : '—'}</td></tr>)}</tbody></table></div></Section><Section title="Milestones"><div className="milestone-grid">{milestones.map((item) => <article className={item.earned ? 'earned' : ''} key={item.label}><span>{item.earned ? '◆' : '◇'}</span><strong>{item.label}</strong><small>{item.earned ? 'Unlocked' : 'Not yet unlocked'}</small></article>)}</div></Section></main>;
}

function Toggle({ label, value, set }: { label: string; value: boolean; set: (value: boolean) => void }) { return <label className="toggle"><span>{label}</span><input type="checkbox" checked={value} onChange={(event) => set(event.target.checked)} /><i aria-hidden="true" /></label>; }
function AccountManager() {
  const [accounts, setAccounts] = useState<Account[]>([]), [error, setError] = useState('');
  const refresh = () => void api.accounts().then(setAccounts).catch((cause) => setError(cause instanceof Error ? cause.message : 'Accounts could not be loaded.'));
  useEffect(refresh, []);
  const create = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(''); const form = event.currentTarget, data = new FormData(form); void api.createAccount({ displayName: String(data.get('displayName')), username: String(data.get('username')), password: String(data.get('password')) }).then(() => { form.reset(); refresh(); }).catch((cause) => setError(cause instanceof Error ? cause.message : 'Account could not be created.')); };
  return <section><h2>Accounts</h2><p>Create private accounts for other people using this instance.</p><form className="account-form" onSubmit={create}><Field label="Display name" name="displayName" autoComplete="off" /><Field label="Username" name="username" autoComplete="off" /><Field label="Initial password" name="password" type="password" autoComplete="new-password" minLength={12} />{error && <p className="form-error" role="alert">{error}</p>}<button>Create account</button></form><ul className="account-list">{accounts.map((account) => <li key={account.id}><span><strong>{account.displayName}</strong><small>@{account.username} · {account.role}</small></span>{account.role !== 'admin' && <button className="secondary danger" onClick={() => { if (window.confirm(`Delete ${account.displayName} and all associated game data?`)) void api.deleteAccount(account.id).then(refresh); }}>Delete</button>}</li>)}</ul></section>;
}
function SettingsPage({ settings, user, save, clear }: { settings: Settings; user: User; save: (value: Settings) => void; clear: (type: 'sessions' | 'statistics' | 'all') => void }) {
  const update = <K extends keyof Settings>(key: K, value: Settings[K]) => save({ ...settings, [key]: value });
  return <main id="main"><div className="page-heading"><p className="eyebrow">Make it yours</p><h1>Settings</h1></div><div className="settings-grid"><section><h2>Appearance</h2><label className="field"><span>Theme</span><select value={settings.theme} onChange={(event) => update('theme', event.target.value as Settings['theme'])}><option value="lavender">Lavender</option><option value="mint">Mint</option><option value="sky">Sky</option><option value="amber">Amber</option><option value="rose">Rose</option><option value="graphite">Graphite</option></select></label><label className="field"><span>Mode</span><select value={settings.mode} onChange={(event) => update('mode', event.target.value as Settings['mode'])}><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select></label><Toggle label="Animations" value={settings.animations} set={(value) => update('animations', value)} /><Toggle label="Reduced motion" value={settings.reducedMotion} set={(value) => update('reducedMotion', value)} /></section><section><h2>Gameplay</h2><Toggle label="Sound effects" value={settings.sound} set={(value) => update('sound', value)} /><Toggle label="Haptic feedback" value={settings.haptics} set={(value) => update('haptics', value)} /><Toggle label="Continue unfinished games automatically" value={settings.autoResume} set={(value) => update('autoResume', value)} /></section><section><h2>Privacy</h2><p>Game data stays on this Playiku instance and is never sent to analytics services.</p><div className="danger-actions"><button className="secondary" onClick={() => clear('sessions')}>Delete saved games</button><button className="secondary danger" onClick={() => clear('statistics')}>Delete statistics</button><button className="danger" onClick={() => clear('all')}>Delete all game data</button></div></section>{user.role === 'admin' && <AccountManager />}</div></main>;
}

function About() { const [manifest, setManifest] = useState<{ version: string; buildDate: string; gitSha: string; license: string; repository: string }>(); useEffect(() => { void api.manifest().then(setManifest); }, []); return <main id="main"><div className="page-heading"><p className="eyebrow">About this app</p><h1>Playiku</h1><p>Casual Games</p></div><section className="about-card"><img src="/playiku-icon.png" alt="Playiku game controller icon" /><dl><div><dt>Version</dt><dd>{manifest?.version ?? 'Loading…'}</dd></div><div><dt>Build date</dt><dd>{manifest?.buildDate ?? 'Loading…'}</dd></div><div><dt>Git commit</dt><dd>{manifest?.gitSha ?? 'Loading…'}</dd></div><div><dt>License</dt><dd>{manifest?.license ?? 'Apache-2.0'}</dd></div></dl><a href={manifest?.repository ?? 'https://github.com/MaroIshiku/playiku'}>View repository</a><p>Third-party license details are included in the repository and release SBOM.</p></section></main>; }

function GamePage({ id, initialState, settings, back, refresh }: { id: GameManifest['id']; initialState?: unknown; settings: Settings; back: () => void; refresh: () => void }) {
  const game = gameById[id], Component = game.component, saveTimer = useRef<number | undefined>(undefined), started = useRef(false), [gameKey, setGameKey] = useState(0), [fresh, setFresh] = useState(false), [daily, setDaily] = useState<{ date: string; seed: string }>();
  useEffect(() => { if (!started.current) { started.current = true; void api.statistic({ gameId: id, outcome: 'started' }); } }, [id]);
  const save = (next: unknown) => { clearTimeout(saveTimer.current); if (game.supportsResume) saveTimer.current = window.setTimeout(() => void api.saveGame(id, next), 350); };
  const complete = (details?: { score?: number; durationMs?: number }) => { clearTimeout(saveTimer.current); if (settings.haptics && 'vibrate' in navigator) navigator.vibrate([35, 30, 70]); if (settings.sound) { const AudioContext = window.AudioContext ?? (window as typeof window & { webkitAudioContext?: typeof window.AudioContext }).webkitAudioContext; if (AudioContext) { const context = new AudioContext(), oscillator = context.createOscillator(), gain = context.createGain(); oscillator.frequency.value = 660; gain.gain.value = .035; oscillator.connect(gain).connect(context.destination); oscillator.start(); oscillator.stop(context.currentTime + .12); } } void Promise.all([api.saveGame(id, {}, true), api.statistic({ gameId: id, outcome: 'won', dailyDate: daily?.date, ...details })]).then(refresh); };
  const startDaily = () => void api.daily(id).then((challenge) => { clearTimeout(saveTimer.current); setDaily({ date: challenge.date, seed: challenge.seed }); setFresh(true); setGameKey((value) => value + 1); });
  return <><header className="game-header"><button className="icon-button secondary" aria-label="Back to games" onClick={back}>←</button><div><h1>{game.name}{daily ? ` · Daily ${daily.date}` : ''}</h1><small>{game.controls}</small></div>{game.supportsDailyChallenge && <button className="secondary" onClick={startDaily}>Daily challenge</button>}<button onClick={() => { clearTimeout(saveTimer.current); setDaily(undefined); setFresh(true); setGameKey((value) => value + 1); void api.saveGame(id, {}, true); }}>New game</button></header><main id="main" className="game-main"><Component key={gameKey} initialState={fresh ? undefined : initialState} dailySeed={daily?.seed} reducedMotion={settings.reducedMotion} onState={save} onComplete={complete} /></main></>;
}

function Shell({ user, onLogout }: { user: User; onLogout: () => void }) {
  const [route, setRoute] = useState<Route>('home'), [state, setState] = useState<AppState>(), [menu, setMenu] = useState(false), [notice, setNotice] = useState('');
  const refresh = () => void api.state().then(setState).catch((cause) => setNotice(cause instanceof Error ? cause.message : 'Could not load game data.'));
  useEffect(refresh, []); useEffect(() => {
    if (!state) return;
    const media = window.matchMedia('(prefers-color-scheme: dark)');
    const apply = () => { document.documentElement.dataset.resolvedMode = state.settings.mode === 'system' ? (media.matches ? 'dark' : 'light') : state.settings.mode; };
    document.documentElement.dataset.theme = state.settings.theme;
    document.documentElement.dataset.mode = state.settings.mode;
    document.documentElement.dataset.motion = state.settings.reducedMotion || !state.settings.animations ? 'reduced' : 'full';
    apply(); media.addEventListener('change', apply);
    return () => media.removeEventListener('change', apply);
  }, [state]);
  const openGame = (id: GameManifest['id']) => { setRoute(`game:${id}`); window.scrollTo(0, 0); };
  if (!state) return <main className="loading-screen"><img src="/playiku-icon.png" alt="" /><p role="status">Loading your games…</p></main>;
  if (route.startsWith('game:')) { const id = route.slice(5) as GameManifest['id']; return <GamePage id={id} initialState={state.activeSessions.find((item) => item.gameId === id)?.state} settings={state.settings} back={() => { refresh(); setRoute('home'); }} refresh={refresh} />; }
  const navigate = (next: Route) => { setRoute(next); setMenu(false); }, saveSettings = (settings: Settings) => { setState({ ...state, settings }); void api.saveSettings(settings).catch(() => { setNotice('Settings could not be saved.'); refresh(); }); }, clear = (type: 'sessions' | 'statistics' | 'all') => { if (!window.confirm('Delete the selected game data? This cannot be undone.')) return; void api.clearHistory(type).then(() => { setNotice('Game data deleted.'); refresh(); }); };
  return <><a className="skip-link" href="#main">Skip to content</a><header className="app-header"><button className="brand" onClick={() => navigate('home')}><img src="/playiku-icon.png" alt="" /><span><strong>Playiku</strong><small>Casual Games</small></span></button><nav aria-label="Primary"><button className="nav-button" aria-current={route === 'home' ? 'page' : undefined} onClick={() => navigate('home')}>Games</button><button className="nav-button desktop-nav" aria-current={route === 'statistics' ? 'page' : undefined} onClick={() => navigate('statistics')}>Statistics</button></nav><div className="profile-wrap"><button className="profile-button" aria-label="Open profile menu" aria-expanded={menu} onClick={() => setMenu((value) => !value)}><span>{user.displayName.slice(0, 1).toUpperCase()}</span><em>{user.displayName}</em></button>{menu && <div className="profile-menu" role="menu"><button role="menuitem" onClick={() => navigate('profile')}>Profile</button><button role="menuitem" onClick={() => navigate('statistics')}>Statistics</button><button role="menuitem" onClick={() => navigate('settings')}>Settings</button><button role="menuitem" onClick={() => navigate('settings')}>Theme</button><button role="menuitem" onClick={() => navigate('about')}>About</button><hr /><button role="menuitem" onClick={onLogout}>Logout</button></div>}</div></header>{notice && <div className="toast" role="status"><span>{notice}</span><button aria-label="Dismiss message" onClick={() => setNotice('')}>×</button></div>}{route === 'home' && <Home state={state} openGame={openGame} toggleFavorite={(id) => { const favorite = !state.favorites.includes(id); setState({ ...state, favorites: favorite ? [...state.favorites, id] : state.favorites.filter((item) => item !== id) }); void api.favorite(id, favorite).catch(refresh); }} />}{route === 'statistics' && <Statistics statistics={state.statistics} />}{route === 'settings' && <SettingsPage settings={state.settings} user={user} save={saveSettings} clear={clear} />}{route === 'profile' && <main id="main"><div className="page-heading"><p className="eyebrow">Your account</p><h1>Profile</h1></div><section className="profile-card"><span className="profile-avatar">{user.displayName.slice(0, 1).toUpperCase()}</span><div><strong>{user.displayName}</strong><small>@{user.username}</small><p>Your preferences, statistics, favorites, and active games are private to this account.</p></div></section></main>}{route === 'about' && <About />}</>;
}

function App() {
  const [status, setStatus] = useState<'loading' | 'setup' | 'login' | 'ready'>('loading'), [user, setUser] = useState<User>();
  useEffect(() => { void api.setupStatus().then(async ({ required }) => { if (required) setStatus('setup'); else { try { const session = await api.session(); setUser(session.user); setStatus('ready'); } catch { setStatus('login'); } } }); const register = () => { if ('serviceWorker' in navigator) void navigator.serviceWorker.register('/sw.js'); }; const online = () => void flushOfflineQueue(); if (document.readyState === 'complete') register(); else window.addEventListener('load', register); window.addEventListener('online', online); return () => { window.removeEventListener('load', register); window.removeEventListener('online', online); }; }, []);
  if (status === 'loading') return <main className="loading-screen"><img src="/playiku-icon.png" alt="" /><p role="status">Opening Playiku…</p></main>;
  if (status === 'setup' || status === 'login') return <AccessScreen setup={status === 'setup'} onReady={(next) => { setUser(next); setStatus('ready'); }} />;
  return user ? <Shell user={user} onLogout={() => void api.logout().finally(() => { setUser(undefined); setStatus('login'); })} /> : null;
}

createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);
